include:
  - template: SAST.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml

stages:
  - build
  - test
  - deploy
  - cleanup

sast:
  stage: test

django_tests:
  stage: test
  image: python:3.12
  variables:
    DJANGO_SETTINGS_MODULE: "CarbonInsight.settings"
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  cache:
    paths:
      - .cache/pip
  before_script:
    - pip install --upgrade pip wheel
    - pip install -r requirements.txt
    - pip install unittest-xml-reporting coverage
  script:
    - cd "$CI_PROJECT_DIR/CarbonInsight"
    # Run migrations
    - python manage.py migrate --noinput
    # Run tests with xml output
    - coverage run --source='.' manage.py test --verbosity=2 --testrunner="xmlrunner.extra.djangotestrunner.XMLTestRunner"
    # Dump coverage report
    - coverage xml -o coverage/cobertura-coverage.xml
    - coverage html -d coverage/htmlcov
    - coverage report
  artifacts:
    when: always
    # GitLab will look here for JUnit XML files and show failures inline. Same for coverage.
    reports:
      junit:
        - CarbonInsight/*.xml
      coverage_report:
        coverage_format: cobertura
        path: CarbonInsight/coverage/cobertura-coverage.xml
    untracked: true

  # Parse coverage % from console output
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'