[build]
builder = "nixpacks"

[deploy]
startCommand = "cd CarbonInsight && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn CarbonInsight.wsgi:application"
healthcheckPath = "/api/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environment]
DJANGO_SETTINGS_MODULE = "CarbonInsight.settings"
PYTHONPATH = "/app/CarbonInsight"