# Generated by Django 5.2 on 2025-05-14 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='co_2_emissions_override',
        ),
        migrations.CreateModel(
            name='ProductEmissionOverrideFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifecycle_stage', models.CharField(choices=[('A1', 'A1 - Raw material supply (and upstream production)'), ('A2', 'A2 - Cradle-to-gate transport to factory'), ('A3', 'A3 - Production'), ('A4', 'A4 - Transport to final destination'), ('A5', 'A5 - Installation'), ('A1-A3', 'A1-A3 - Raw material supply and production'), ('A4-A5', 'A4-A5 - Transport to final destination and installation'), ('B1', 'B1 - Usage phase'), ('B2', 'B2 - Maintenance'), ('B3', 'B3 - Repair'), ('B4', 'B4 - Replacement'), ('B5', 'B5 - Update/upgrade, refurbishing'), ('B6', 'B6 - Operational energy use'), ('B7', 'B7 - Operational water use'), ('B1-B7', 'B1-B7 - Entire usage phase'), ('C1', 'C1 - Reassembly'), ('C2', 'C2 - Transport to recycler'), ('C3', 'C3 - Recycling, waste treatment'), ('C4', 'C4 - Landfill'), ('C1-C4', 'C1-C4 - Decommissioning'), ('C2-C4', 'C2-C4 - Transport to recycler and landfill'), ('D', 'D - Reuse'), ('Other', 'Other')], default='Other', max_length=255)),
                ('co_2_emission_factor', models.FloatField()),
                ('emission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='override_factors', to='core.product')),
            ],
        ),
    ]
