# Generated by Django 5.2 on 2025-05-14 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_product_co_2_emissions_override_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_prompt', models.TextField()),
                ('instructions', models.TextField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversation_logs', to='core.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI conversation log',
                'verbose_name_plural': 'AI conversation logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
