# Generated by Django 5.2 on 2025-05-09 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productsharingrequest',
            unique_together={('product', 'requester')},
        ),
    ]
