# Generated by Django 5.2 on 2025-05-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_productsharingrequest_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endoflifeemissionreference',
            name='name',
        ),
        migrations.RemoveField(
            model_name='materialemissionreference',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productionenergyemissionreference',
            name='name',
        ),
        migrations.RemoveField(
            model_name='transportemissionreference',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userenergyemissionreference',
            name='name',
        ),
        migrations.AddField(
            model_name='endoflifeemissionreference',
            name='common_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='endoflifeemissionreference',
            name='technical_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='materialemissionreference',
            name='common_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='materialemissionreference',
            name='technical_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productionenergyemissionreference',
            name='common_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productionenergyemissionreference',
            name='technical_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transportemissionreference',
            name='common_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transportemissionreference',
            name='technical_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userenergyemissionreference',
            name='common_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userenergyemissionreference',
            name='technical_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='endoflifeemissionreference',
            constraint=models.CheckConstraint(condition=models.Q(('common_name__isnull', False), ('technical_name__isnull', False), _connector='OR'), name='common_or_technical_name_not_null_end_of_life_emission_reference'),
        ),
        migrations.AddConstraint(
            model_name='materialemissionreference',
            constraint=models.CheckConstraint(condition=models.Q(('common_name__isnull', False), ('technical_name__isnull', False), _connector='OR'), name='common_or_technical_name_not_null_material_emission_reference'),
        ),
        migrations.AddConstraint(
            model_name='productionenergyemissionreference',
            constraint=models.CheckConstraint(condition=models.Q(('common_name__isnull', False), ('technical_name__isnull', False), _connector='OR'), name='common_or_technical_name_not_null_production_energy_reference'),
        ),
        migrations.AddConstraint(
            model_name='transportemissionreference',
            constraint=models.CheckConstraint(condition=models.Q(('common_name__isnull', False), ('technical_name__isnull', False), _connector='OR'), name='common_or_technical_name_not_null_transport_emission_reference'),
        ),
        migrations.AddConstraint(
            model_name='userenergyemissionreference',
            constraint=models.CheckConstraint(condition=models.Q(('common_name__isnull', False), ('technical_name__isnull', False), _connector='OR'), name='common_or_technical_name_not_null_user_energy_reference'),
        ),
    ]
