# Generated by Django 5.2 on 2025-05-16 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aiconversationlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='manufacturer',
            new_name='manufacturer_name',
        ),
    ]
