# Generated by Django 5.2 on 2025-05-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_endoflifeemissionreference_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endoflifeemissionreferencefactor',
            name='co_2_emission_factor',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='materialemissionreferencefactor',
            name='co_2_emission_factor',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='productionenergyemissionreferencefactor',
            name='co_2_emission_factor',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transportemissionreferencefactor',
            name='co_2_emission_factor',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userenergyemissionreferencefactor',
            name='co_2_emission_factor',
            field=models.FloatField(),
        ),
    ]
