# Generated by Django 5.2 on 2025-05-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_manufacturer_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='family',
            field=models.CharField(default='Unknown product family', max_length=255),
            preserve_default=False,
        ),
    ]
