# Generated by Django 5.2 on 2025-05-16 12:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reference_impact_unit',
            field=models.CharField(choices=[('A1', 'A1 - Raw material supply (and upstream production)'), ('A2', 'A2 - Cradle-to-gate transport to factory'), ('A3', 'A3 - Production'), ('A4', 'A4 - Transport to final destination'), ('A5', 'A5 - Installation'), ('A1-A3', 'A1-A3 - Raw material supply and production'), ('A4-A5', 'A4-A5 - Transport to final destination and installation'), ('B1', 'B1 - Usage phase'), ('B2', 'B2 - Maintenance'), ('B3', 'B3 - Repair'), ('B4', 'B4 - Replacement'), ('B5', 'B5 - Update/upgrade, refurbishing'), ('B6', 'B6 - Operational energy use'), ('B7', 'B7 - Operational water use'), ('B1-B7', 'B1-B7 - Entire usage phase'), ('C1', 'C1 - Reassembly'), ('C2', 'C2 - Transport to recycler'), ('C3', 'C3 - Recycling, waste treatment'), ('C4', 'C4 - Landfill'), ('C1-C4', 'C1-C4 - Decommissioning'), ('C2-C4', 'C2-C4 - Transport to recycler and landfill'), ('D', 'D - Reuse'), ('Other', 'Other')], default='Other', max_length=255),
        ),
        migrations.AlterField(
            model_name='materialemission',
            name='reference',
            field=models.ForeignKey(help_text='Reference values for the material emission', on_delete=django.db.models.deletion.CASCADE, related_name='material_emissions', to='core.materialemissionreference'),
        ),
        migrations.AlterField(
            model_name='materialemission',
            name='weight',
            field=models.FloatField(help_text='Weight of the material in kg', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='productionenergyemission',
            name='energy_consumption',
            field=models.FloatField(help_text='Energy consumption in kWh', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='productionenergyemission',
            name='reference',
            field=models.ForeignKey(help_text='Reference values for the production energy emission', on_delete=django.db.models.deletion.CASCADE, related_name='production_emissions', to='core.productionenergyemissionreference'),
        ),
        migrations.AlterField(
            model_name='transportemission',
            name='distance',
            field=models.FloatField(help_text='Distance of the transport in km', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='transportemission',
            name='reference',
            field=models.ForeignKey(help_text='Reference values for the transport emission', on_delete=django.db.models.deletion.CASCADE, related_name='transport_emissions', to='core.transportemissionreference'),
        ),
        migrations.AlterField(
            model_name='transportemission',
            name='weight',
            field=models.FloatField(help_text='Weight of the transported product in kg', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='userenergyemission',
            name='energy_consumption',
            field=models.FloatField(help_text='Energy consumption in kWh', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='userenergyemission',
            name='reference',
            field=models.ForeignKey(help_text='Reference values for the user energy emission', on_delete=django.db.models.deletion.CASCADE, related_name='user_emissions', to='core.userenergyemissionreference'),
        ),
    ]
