# Generated by Django 5.2 on 2025-05-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_reference_impact_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reference_impact_unit',
            field=models.CharField(choices=[('g', 'Gram'), ('kg', 'Kilogram'), ('t', 'Ton'), ('ml', 'Milliliter'), ('l', 'Liter'), ('m3', 'Cubic meter'), ('m2', 'Square meter'), ('pc', 'Piece'), ('kWh', 'Kilowatt hour'), ('Other', 'Other')], default='Other', max_length=255),
        ),
    ]
