# Generated by Django 5.2 on 2025-05-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_product_reference_impact_unit'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productbomlineitem',
            constraint=models.CheckConstraint(condition=models.Q(('parent_product', models.F('line_item_product')), _negated=True), name='prevent_self_reference_bom_line_item'),
        ),
    ]
