# Generated by Django 5.2 on 2025-05-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_productbomlineitem_prevent_self_reference_bom_line_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='emission',
            name='pcf_calculation_method',
            field=models.CharField(choices=[('EN 15804', 'EN 15804 - Product Category Rules (PCR) for construction products'), ('GHG Protocol', 'GHG Protocol - Corporate Standard'), ('IEC TS 63058', 'IEC TS 63058 - Product Category Rules (PCR) for electrical and electronic products'), ('IEC 63366', 'IEC 63366 - Product Category Rules (PCR) for electrical and electronic products'), ('ISO 14040/14044', 'ISO 14040/14044 - Life Cycle Assessment (LCA) principles, framework, and methodology'), ('ISO 14067', 'ISO 14067 - Carbon footprint of products'), ('PEP Ecopassport', 'PEP Ecopassport - Product Environmental Profile (PEP) for electrical and electronic products'), ('PACT v2.0.0', 'PACT v2.0.0 - Product Category Rules (PCR) for electrical and electronic products'), ('PACT v1.0.1', 'PACT v1.0.1 - Product Category Rules (PCR) for electrical and electronic products'), ('PACT v3.0.0', 'PACT v3.0.0 - Product Category Rules (PCR) for electrical and electronic products'), ('TFS v2', 'TFS v2 - Product Category Rules (PCR) for electrical and electronic products'), ('TFS v3', 'TFS v3 - Product Category Rules (PCR) for electrical and electronic products'), ('Catena-X v2', 'Catena-X v2 - Product Category Rules (PCR) for electrical and electronic products'), ('Catena-X v1', 'Catena-X v1 - Product Category Rules (PCR) for electrical and electronic products'), ('Catena-X v3', 'Catena-X v3 - Product Category Rules (PCR) for electrical and electronic products'), ('BS PAS 2050', 'BS PAS 2050 - Specification for the assessment of the life cycle greenhouse gas emissions of goods and services'), ('IEC 63372', 'IEC 63372 - Product Category Rules (PCR) for electrical and electronic products'), ('Other', 'Other')], default='ISO 14040/14044', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='pcf_calculation_method',
            field=models.CharField(choices=[('EN 15804', 'EN 15804 - Product Category Rules (PCR) for construction products'), ('GHG Protocol', 'GHG Protocol - Corporate Standard'), ('IEC TS 63058', 'IEC TS 63058 - Product Category Rules (PCR) for electrical and electronic products'), ('IEC 63366', 'IEC 63366 - Product Category Rules (PCR) for electrical and electronic products'), ('ISO 14040/14044', 'ISO 14040/14044 - Life Cycle Assessment (LCA) principles, framework, and methodology'), ('ISO 14067', 'ISO 14067 - Carbon footprint of products'), ('PEP Ecopassport', 'PEP Ecopassport - Product Environmental Profile (PEP) for electrical and electronic products'), ('PACT v2.0.0', 'PACT v2.0.0 - Product Category Rules (PCR) for electrical and electronic products'), ('PACT v1.0.1', 'PACT v1.0.1 - Product Category Rules (PCR) for electrical and electronic products'), ('PACT v3.0.0', 'PACT v3.0.0 - Product Category Rules (PCR) for electrical and electronic products'), ('TFS v2', 'TFS v2 - Product Category Rules (PCR) for electrical and electronic products'), ('TFS v3', 'TFS v3 - Product Category Rules (PCR) for electrical and electronic products'), ('Catena-X v2', 'Catena-X v2 - Product Category Rules (PCR) for electrical and electronic products'), ('Catena-X v1', 'Catena-X v1 - Product Category Rules (PCR) for electrical and electronic products'), ('Catena-X v3', 'Catena-X v3 - Product Category Rules (PCR) for electrical and electronic products'), ('BS PAS 2050', 'BS PAS 2050 - Specification for the assessment of the life cycle greenhouse gas emissions of goods and services'), ('IEC 63372', 'IEC 63372 - Product Category Rules (PCR) for electrical and electronic products'), ('Other', 'Other')], default='ISO 14040/14044', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='reference_impact_unit',
            field=models.CharField(choices=[('g', 'Gram'), ('kg', 'Kilogram'), ('t', 'Ton'), ('ml', 'Milliliter'), ('l', 'Liter'), ('m3', 'Cubic meter'), ('m2', 'Square meter'), ('pc', 'Piece'), ('kWh', 'Kilowatt hour'), ('Other', 'Other')], default='pc', max_length=255),
        ),
    ]
