# Generated by Django 5.2 on 2025-05-22 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_materialemission_reference_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('supplier', 'name', 'manufacturer_name', 'sku')},
        ),
    ]
