# Generated by Django 5.2 on 2025-05-28 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_product_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emissionoverridefactor',
            old_name='co_2_emission_factor',
            new_name='co_2_emission_factor_biogenic',
        ),
        migrations.RenameField(
            model_name='materialemissionreferencefactor',
            old_name='co_2_emission_factor',
            new_name='co_2_emission_factor_biogenic',
        ),
        migrations.RenameField(
            model_name='productemissionoverridefactor',
            old_name='co_2_emission_factor',
            new_name='co_2_emission_factor_biogenic',
        ),
        migrations.RenameField(
            model_name='productionenergyemissionreferencefactor',
            old_name='co_2_emission_factor',
            new_name='co_2_emission_factor_biogenic',
        ),
        migrations.RenameField(
            model_name='transportemissionreferencefactor',
            old_name='co_2_emission_factor',
            new_name='co_2_emission_factor_biogenic',
        ),
        migrations.RenameField(
            model_name='userenergyemissionreferencefactor',
            old_name='co_2_emission_factor',
            new_name='co_2_emission_factor_biogenic',
        ),
    ]
