# Generated by Django 5.2 on 2025-05-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_co_2_emission_factor_emissionoverridefactor_co_2_emission_factor_biogenic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionoverridefactor',
            name='co_2_emission_factor_non_biogenic',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialemissionreferencefactor',
            name='co_2_emission_factor_non_biogenic',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productemissionoverridefactor',
            name='co_2_emission_factor_non_biogenic',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionenergyemissionreferencefactor',
            name='co_2_emission_factor_non_biogenic',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportemissionreferencefactor',
            name='co_2_emission_factor_non_biogenic',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userenergyemissionreferencefactor',
            name='co_2_emission_factor_non_biogenic',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
