# Generated by Django 5.2 on 2025-06-02 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_emissionoverridefactor_co_2_emission_factor_biogenic_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaterialEmissionReferenceFactor',
        ),
    ]
