# Generated by Django 5.2 on 2025-06-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_materialemission_reference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaterialEmissionReference',
        ),
    ]
