# Generated by Django 5.2 on 2025-06-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_delete_materialemissionreference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaterialEmission',
        ),
    ]
