# Generated by Django 5.2 on 2025-06-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_delete_materialemission'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='auto_approve_product_sharing_requests',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='is_reference',
            field=models.BooleanField(default=False),
        ),
    ]
