# Generated by Django 5.2 on 2025-06-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_company_auto_approve_product_sharing_requests_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(condition=models.Q(('is_reference', True)), fields=('is_reference',), name='unique_reference_company'),
        ),
    ]
