# Generated by Django 5.2 on 2025-06-13 16:42

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_emission_productemissionoverridefactor_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emission',
            options={'base_manager_name': 'non_polymorphic', 'verbose_name': 'Emission', 'verbose_name_plural': 'Emissions'},
        ),
        migrations.AlterModelManagers(
            name='emission',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='productionenergyemission',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='transportemission',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='userenergyemission',
            managers=[
                ('non_polymorphic', django.db.models.manager.Manager()),
            ],
        ),
    ]
